### ISSUE TITLE
Can't add new logins via django admin

### ISSUE THREAD

**Issue by honza** [SheepDogInc/ssheepdog#4]
This view is broken:

```
http://localhost:8000/admin/ssheepdog/login/add/
```

This is thrown:

```
DoesNotExist at /admin/ssheepdog/login/add/
No exception supplied
```

I think it's related to that `DirtyFieldsMixin`, @wolfe

**Comment by wolfe** [comment]
Yup --- That mixin is something I'm futzing with.  I admin it; it does not yet have any tests.

I pushed a fix, but no tests yet.
