### ISSUE TITLE
Confusing admin UI

### ISSUE THREAD

**Issue by honza** [SheepDogInc/ssheepdog#6]
When adding a new `Login` instance through the Django admin, the _Machine_ dropdown has a list of machines that very hard to distinguish from one another. I realize that it's partially naming most of them either _live_ or _staging_ but there should probably be a better UI for this.

**Comment by wolfe** [comment]
Would it not suffice to make a better **unicode** method for Machines:
  return "%s (%s)" % (self.nickname, self.hostname or self.ip)

On Sun, Jan 29, 2012 at 2:07 PM, Honza Pokorny <
reply@reply.github.com

> wrote:
> 
> When adding a new `Login` instance through the Django admin, the _Machine_
> dropdown has a list of machines that very hard to distinguish from one
> another. I realize that it's partially naming most of them either _live_ or
> _staging_ but there should probably be a better UI for this.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SheepDogInc/ssheepdog/issues/6

## 

David Wolfe, PhD
R&D Team Lead
SheepDogInc.ca | Information's best friend.

1-888-807-5765
902-442-8228 direct
902-446-7043 fax

**Comment by honza** [comment]
Actually, yes...

I opted for `return "%s (%s)" % (self.nickname, self.client.nickname)`.
